// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by Sucrose.Avro.CodeGen, version 1.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ConfluentSample
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class AMEssage : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"AMEssage\",\"namespace\":\"ConfluentSample\",\"fields\":[{\"name" +
				"\":\"noOfHeads\",\"type\":\"int\"},{\"name\":\"id\",\"type\":\"int\"}]}");
		private int _noOfHeads;
		private int _id;
		public virtual Schema Schema
		{
			get
			{
				return AMEssage._SCHEMA;
			}
		}
		public int noOfHeads
		{
			get
			{
				return this._noOfHeads;
			}
			set
			{
				this._noOfHeads = value;
			}
		}
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.noOfHeads;
			case 1: return this.id;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.noOfHeads = (System.Int32)fieldValue; break;
			case 1: this.id = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
