name: .NET Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '8.x' # specify your .NET version
        dotnet-quality: 'signed' # specify your .NET version

    - name: Restore dependencies
      run: dotnet restore Sucrose.Avro.CodeGen-build.sln

    - name: Build
      run: dotnet build --no-restore
    - name: Package
      run:  |
        dotnet pack Sucrose.Avro.CodeGen-build.sln -o ../../ -c release
        dotnet nuget push ../../*.nupkg -k $nuget_api_key -s "nuget.org"
  